server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://ec2-15-164-100-247.ap-northeast-2.compute.amazonaws.com:5432/test
    username: connect
    password: connect$1324
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL14Dialect
    properties:
      hibernate:
        format_sql: true

